import { createHash } from "node:crypto";
import { z } from "zod";
export const STOP_CPU_COMMAND = "docker exec zabbix-cpu-simulator pkill -f 'stress-ng --cpu'" as const;
export const STOP_CPU_ACTION = "simulator.stop-cpu-load" as const;
const time=z.iso.datetime({offset:true});const hash=z.string().regex(/^[a-f0-9]{64}$/u);
export const incidentEnvelopeSchema=z.object({alertId:z.string().min(1),dedupKey:hash,host:z.string().min(1),monitorRef:z.string().min(1),scope:z.string().min(1),severity:z.number().int().min(1).max(5),source:z.enum(["zabbix","datadog"]),startedAt:time,tags:z.record(z.string(),z.string())});
export const hypothesisSchema=z.object({statement:z.string().min(1),confidence:z.number().min(0).max(1),requiredEvidence:z.array(z.string()).min(1),falsifier:z.string().min(1),status:z.enum(["confirmed","refuted","inconclusive"])});
export const evidenceSchema=z.object({id:z.string().min(1),trust:z.enum(["verified","untrusted"]),provenance:z.enum(["tool","rag"]),freshness:time,logicalClock:z.number().int().nonnegative(),reference:z.string().min(1)});
export const actionPlanSchema=z.object({action:z.literal(STOP_CPU_ACTION),target:z.literal("zabbix-cpu-simulator"),command:z.literal(STOP_CPU_COMMAND),preconditions:z.array(z.string()).min(1),rollback:z.literal("Reapply CPU load manually with scripts/set-cpu-load.sh."),blastRadius:z.literal("single container zabbix-cpu-simulator"),evidenceRefs:z.array(z.string()).min(1),policyVersion:z.string().min(1),proposedAt:time,expiresAt:time}).superRefine((plan,ctx)=>{if(Date.parse(plan.expiresAt)-Date.parse(plan.proposedAt)!==600000)ctx.addIssue({code:"custom",message:"Action plan TTL must be ten minutes."});});
export const approvalSchema=z.object({id:z.string().min(1),incidentId:z.string().min(1),actionDigest:hash,approverSlackUserId:z.string().min(1),role:z.literal("sre-approver"),issuedAt:time,expiresAt:time});
export const journalEventSchema=z.object({eventId:z.string().min(1),incidentId:z.string().min(1),type:z.enum(["incident.received","analysis.recorded","action.proposed","approval.recorded","action.receipted"]),occurredAt:time,logicalClock:z.number().int().nonnegative(),payload:z.record(z.string(),z.string())});
export type IncidentEnvelope=z.infer<typeof incidentEnvelopeSchema>;export type Hypothesis=z.infer<typeof hypothesisSchema>;export type Evidence=z.infer<typeof evidenceSchema>;export type ActionPlan=z.infer<typeof actionPlanSchema>;export type Approval=z.infer<typeof approvalSchema>;export type JournalEvent=z.infer<typeof journalEventSchema>;
export type TelemetryReadRequest=Readonly<{incident:IncidentEnvelope;operation:"problem.get"|"item.get"|"history.get"|"host.get"}>;export interface TelemetrySource{read(request:TelemetryReadRequest):Promise<readonly Evidence[]>;}export type McpToolDefinition=Readonly<{name:"zbx.get_problem"|"zbx.get_item"|"zbx.get_item_history"|"zbx.get_host";readOnly:true}>;
const zabbix=z.object({eventId:z.string().min(1),eventTime:time,host:z.string().min(1),itemKey:z.literal("system.cpu.util"),itemValue:z.string().min(1),severity:z.number().int().min(0).max(5),triggerName:z.string().min(1)});const datadog=z.object({alertId:z.string().min(1),alertQuery:z.string().min(1),alertTransition:z.string().min(1),eventMessage:z.string().min(1),eventTitle:z.string().min(1),tags:z.array(z.string()).min(1)});
function dedup(source:IncidentEnvelope["source"],alertId:string,scope:string):string{return createHash("sha256").update(source+":"+alertId+":"+scope).digest("hex");}
export function normalizeZabbixWebhook(input:unknown):IncidentEnvelope{const raw=zabbix.parse(input);return incidentEnvelopeSchema.parse({alertId:raw.eventId,dedupKey:dedup("zabbix",raw.eventId,raw.host),host:raw.host,monitorRef:raw.triggerName,scope:raw.host,severity:Math.min(raw.severity+1,5),source:"zabbix",startedAt:raw.eventTime,tags:{item_key:raw.itemKey,item_value:raw.itemValue}});}
export function normalizeDatadogWebhook(input:unknown,startedAt:string):IncidentEnvelope{const raw=datadog.parse(input);const tags=Object.fromEntries(raw.tags.map(tag=>{const at=tag.indexOf(":");return at>0?[tag.slice(0,at),tag.slice(at+1)]:[tag,"true"];}));const host=tags["host"]??"unknown-host";return incidentEnvelopeSchema.parse({alertId:raw.alertId,dedupKey:dedup("datadog",raw.alertId,host),host,monitorRef:raw.alertQuery,scope:host,severity:4,source:"datadog",startedAt,tags});}
export function digestActionPlan(input:ActionPlan):string{const plan=actionPlanSchema.parse(input);const canonical=JSON.stringify(Object.fromEntries(Object.entries(plan).sort(([left],[right])=>left.localeCompare(right))));return createHash("sha256").update(canonical).digest("hex");}export const JSON_SCHEMAS = {
  incidentEnvelope: { "$schema": "https://json-schema.org/draft/2020-12/schema", "$id": "sre://contracts/incident-envelope/v1", type: "object", required: ["source","alertId","monitorRef","severity","host","scope","tags","startedAt","dedupKey"] },
  actionPlan: { "$schema": "https://json-schema.org/draft/2020-12/schema", "$id": "sre://contracts/action-plan/v1", type: "object", required: ["action","target","command","preconditions","rollback","blastRadius","evidenceRefs","policyVersion","proposedAt","expiresAt"] },
  approval: { "$schema": "https://json-schema.org/draft/2020-12/schema", "$id": "sre://contracts/approval/v1", type: "object", required: ["id","incidentId","actionDigest","approverSlackUserId","role","issuedAt","expiresAt"] }
} as const;
